dataset: cosmos_qa	No info from HuggingFace
dataset: cosmos_qa	splits: train: 25262 rows, test: 6963 rows, val: 2985 rows
dataset: cosmos_qa	split: train	columns: id, context, question, answer0, answer1, answer2, answer3, label
***ERROR***
model: None
data: H:cosmos_qa
eqn: None
splits: train
split: train
task: None
error: (<class 'requests.exceptions.HTTPError'>, HTTPError('405 Client Error: Not Allowed for url: https://huggingface.co/api/models-tags-by-type'), <traceback object at 0x7fe9007c8e40>)
