dataset: yelp_polarity	No info from HuggingFace
dataset: yelp_polarity,plain_text	splits: train: 560000 rows, test: 38000 rows
dataset: yelp_polarity,plain_text	split: train	columns: text, label
dataset: yelp_polarity,plain_text	labels: 1, 2
***ERROR***
model: None
data: H:yelp_polarity
eqn: None
splits: train
split: train
task: None
error: (<class 'requests.exceptions.HTTPError'>, HTTPError('405 Client Error: Not Allowed for url: https://huggingface.co/api/models-tags-by-type'), <traceback object at 0x7f7771638580>)
